name: xsbg
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^5.0.0-nullsafety.5
  permission_handler: ^5.1.0+2
  dartx: ^0.6.0
  qr: ^2.0.0
  font_awesome_flutter: ^8.11.0
  cupertino_icons: ^1.0.1
  uuid: ^3.0.1
  equatable: ^1.2.5
  grpc: ^3.0.0
  protobuf: ^2.0.0
  qr_code_scanner: ^0.4.0-nullsafety.0
  rxdart: ^0.25.0
  wifi_info_flutter: ^1.0.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  hive_generator: ^0.8.2
  flutter_launcher_icons: ^0.9.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icons.json
    - assets/parchment.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"